Taskmate/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from todolist import views

urlpatterns = [
	path('', views.home,name='home'),
    path('contact/', views.contacts , name='contact'),
    path('about/', views.about , name='about'),
    path('admin/', admin.site.urls),
    path('task/', include('todolist.urls')),
    path('account/', include('userapp.urls')),
]

todolist/urls.py
from django.urls import path
from todolist import views

app_name = 'todolist'

urlpatterns = [
	path('', views.todolist , name='Todolist'),
	path('delete/<task_id>', views.deletetask , name='delete'),
	path('update/<task_id>', views.updatetask , name='update'),
	path('complete/<task_id>', views.complete , name='complete'),
	
]

userapp/urls.py
from django.urls import path
from userapp import views
from django.contrib.auth import views as auth_views

app_name = 'userapp'

urlpatterns = [
	path('register', views.register , name='register'),
	path('login', auth_views.LoginView.as_view(template_name='login.html') , name='login'),
	path('logout', auth_views.LogoutView.as_view(template_name='logout.html') , name='logout'),

]

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class todo(models.Model):
	owner = models.ForeignKey(User,on_delete=models.CASCADE,default=None)
	task = models.CharField(max_length=300)
	done = models.BooleanField(default=False)


	def __str__(self):
		return self.task

userapp/models.py
from django.db import models

# Create your models here.

todolist/forms.py
from django import forms
from todolist.models import todo

class taskform(forms.ModelForm):
	class Meta:
		model = todo
		fields = ('task','done') 

userapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class customform(UserCreationForm):
	email= forms.EmailField()

	class Meta:
		model = User
		fields = ['username','email','password1','password2']

todolist/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from django.http import HttpResponse ,HttpResponseRedirect
from todolist.models import todo
from todolist.forms import taskform 
from django.views.generic import CreateView,UpdateView,DeleteView
from django.contrib import messages
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required
def todolist(request):
	if request.method=="POST":
		form =taskform(request.POST)
		if form.is_valid():
			print("inside valid")
			form=form.save(commit=False)
			form.owner = request.user
			form.save()
			messages.success(request,("New Task added to the list"))
		return redirect('todolist:Todolist')
	
			
	else:	
		taks = todo.objects.filter(owner=request.user)
		paginator = Paginator(taks , 5)
		page = request.GET.get('pg')
		taks = paginator.get_page(page)
		dic = {'list': taks}
		return render(request,'tdtemp.html',context=dic)

def contacts(request):
	return render(request,'contact.html',{})

def about(request):
	return render(request,'about.html',{})


def home(request):
	return render(request,'home.html',{})


def deletetask(request,task_id):
	task = todo.objects.filter(id=task_id)
	if(task.manage==request.user):
		task.delete()
		return redirect('todolist:Todolist')
	else:
		messages.error(request,("Access Restricted"))	


def updatetask(request,task_id):
	if request.method=="POST":
		taskobj = todo.objects.get(pk=task_id)
		form = taskform(request.POST,instance=taskobj)
		if form.is_valid():
			form.save()

			messages.success(request,("successfully updated"))
		return redirect('todolist:Todolist')
	else:	
		taskobj = todo.objects.get(pk=task_id)
		return render(request,'update.html',{'taskobj':taskobj})


def complete(request,task_id):

	task = todo.objects.get(id=task_id)
	if(task.manage==request.user):
		if(task.done==True):
			task.done=False
			task.save()
		else:
			task.done=True
			task.save()	
		return redirect('todolist:Todolist')
	else:
		messages.error(request,("Access Restricted"))	

userapp/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from userapp.forms import customform
# Create your views here.
def register(request):
	if request.method=="POST":
		form = customform(request.POST)
		if form.is_valid():
			form.save()
			messages.success(request,("Account created"))
			return redirect('userapp:register')
		

			
	register_form = customform()
	return render(request,'register.html',{'register_form':register_form})

templates/base.html
<!DOCTYPE html>
{%load static%}
<html>
<head>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  {%block title%}
	<title></title>
  {%endblock title%}
</head>
<body class="bg-light">
	<nav class="navbar navbar-expand-md navbar-white bg-white mb-4">
  <a class="navbar-brand" href="#"><img src="{%static 'images/logo.jpg'%}" alt="logo">TaskMAte</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/">HOME</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%url 'todolist:Todolist'%}">Todolist</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%url 'contact'%}">Contact us</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%url 'about'%}">About us</a>
      </li>
    </ul>
    
  </div>
  {%if user.is_authenticated%}
  <div class="form-inline mt-2 mt-md-0">
        <h5 style="margin-right: 20px">Welcome ,{{user.username}}</h5>
      <a href="{%url 'userapp:logout'%}"><button class="btn btn-outline-success my-2 my-sm-0" type="submit">Logout</button></a>
    </div>
  {%else%}
  <div class="form-inline mt-2 mt-md-0">
        <h4 style="margin-right: 20px">{{user.username}}</h4>
      <a style="margin-right: 15px" href="{%url 'userapp:login'%}"><button class="btn btn-outline-success my-2 my-sm-0" type="submit">Login</button></a>
      <a href="{%url 'userapp:login'%}"><button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Register</button></a>
    </div>
  {%endif%}

</nav>

{%block body_block%}


{%endblock%}

</body>
</html>

todolist/templates/about.html
<!DOCTYPE html>
{%extends 'base.html'%}
{%block body_block%}
<h3>About us</h3>
{%endblock%}

todolist/templates/contact.html
{%extends 'base.html'%}
{%block title%}
<title>Contact</title>
{%endblock title%}
{%block body_block%}
<h3>contact us on 8475995855</h3>
{%endblock%}

todolist/templates/home.html
<!DOCTYPE html>
{%extends 'base.html'%}
{%block title%}
<title>Home</title>
{%endblock title%}

{%block body_block%}
<h1>Welcome to the Homepage</h1>
{%endblock%}

todolist/templates/tdtemp.html
<!DOCTYPE html>
{%extends 'base.html'%}
{%block title%}
<title>Todolist</title>
{%endblock title%}
{%block body_block%}


<div class="container">
	{% for m in messages%}
	<div class="alert alert-info alert-dismissible fade show" role="alert">
  		{{m}}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
	{%endfor%}




	<form method="POST">
	{%csrf_token%}
  <div class="form-group row">
    <label class="col-lg-2" style="margin-right: 0px;"><h4>Enter Task :</h4></label>
    <input type="text" class="form-control col-8" name="task" placeholder="Enter the task here" >
  <button type="submit" class="btn btn-primary col-1" style="margin-bottom: 20px;margin-left: 30px">Add Task</button>
  </div>
</form>
</div>

<div class="container">
<table class="table table-striped table-bordered table-hover table-condensed">
	<thead class="thead-dark" >
		<th class="col-7">Task</th>
		<th>Edit</th>
		<th>Delete</th>
		<th class="col-2">Status</th>
		
	</thead>
	
	{%for i in list%}
	{%if i.done%}
	<tr class="table-success">
		<td><del>{{i.task}}</del></td>
		<td><a href="{%url 'todolist:update' i.id %}"><button type="button" class="btn btn-secondary">Edit</button></a></td>
		<td><a href="{%url 'todolist:delete' i.id %}"><button type="button" class="btn btn-danger">Delete</button></a></td>
		<td><a href="{%url 'todolist:complete' i.id %}"><button type="button" class="btn btn-success">Complete</button></a></td>
		
	</tr>
	{%else%}
	<tr >
		<td>{{i.task}}</td>
		<td><a href="{%url 'todolist:update' i.id %}"><button type="button" class="btn btn-secondary">Edit</button></a></td>
		<td><a href="{%url 'todolist:delete' i.id %}"><button type="button" class="btn btn-danger">Delete</button></a></td>
		<td><a href="{%url 'todolist:complete' i.id %}"><button type="button" class="btn btn-warning">Pending</button></a></td>
		
	</tr>

	{%endif%}
	{%endfor%}
	
</table>

<nav aria-label="Page navigation example">
  <ul class="pagination">
    <li class="page-item"><a class="page-link" href="?pg=1"><<</a></li>

    {%if list.has_previous%}
    <li class="page-item"><a class="page-link" href="?pg={{list.previous_page_number}}">{{list.previous_page_number}}</a></li>
    {%endif%}
    <li class="page-item"><a class="page-link" href="?pg={{list.number}}">{{list.number}}</a></li>
     {%if list.has_next%}
    <li class="page-item"><a class="page-link" href="?pg={{list.next_page_number}}">{{list.next_page_number}}</a></li>
 	    {%endif%}
    <li class="page-item"><a class="page-link" href="?pg={{list.paginator.num_pages}}">>></a></li>

  </ul>
</nav>
</div>

{%endblock%}

todolist/templates/update.html
<!DOCTYPE html>
{%extends 'base.html'%}
{%block title%}
<title>Update</title>
{%endblock title%}
{%block body_block%}

<div class="container">
	{%if taskobj.owner == request.user%}
	<h1 style="text-align: center;">update your todo element</h1>
	<form method="POST">
	{%csrf_token%}
  <div class="form-group row">
    <label class="col-lg-2" style="margin-right: 0px;"><h4></h4></label>
    <input type="text" class="form-control col-8" name="task" placeholder="{{taskobj.task}}" value="{{taskobj.task}}" >
    <input type="hidden"  name="done"  value="{{taskobj.done}}" >
  <button type="submit" class="btn btn-primary col-1" style="margin-bottom: 20px;margin-left: 30px">Update</button>
  </div>
</form>
</div>
</div>
{%else%}
	<h5>Access Restricted!!</h5>
{%endif%}	
{%endblock%}

userapp/templates/login.html
<!DOCTYPE html>
{%extends 'base.html'%}
{%load crispy_forms_tags %}
{%block title%}
<title>Login</title>
{%endblock title%}
{%block body_block%}
<div class="container">
	<div class="container">
	{% for m in messages%}
	<div class="alert alert-info alert-dismissible fade show" role="alert">
  		{{m}}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
	{%endfor%}



 

<form method="POST" class="col-6">

	{{form|crispy}}
	{%csrf_token%}
	<div class="container">
<button class="btn btn-primary">Login</button>
</form>
</div>
{%endblock%}

userapp/templates/logout.html
<!DOCTYPE html>
{%extends 'base.html'%}
{%load crispy_forms_tags %}
{%block title%}
<title>Logout</title>
{%endblock title%}
{%block body_block%}
<div class="container">

<h4>Logged out of taskmate,thank u for using our site</h4>

 

</div>
{%endblock%}

userapp/templates/register.html
<!DOCTYPE html>
{%extends 'base.html'%}
{%load crispy_forms_tags %}
{%block title%}
<title>Register</title>
{%endblock title%}
{%block body_block%}
<div class="container">
	<div class="container">
	{% for m in messages%}
	<div class="alert alert-info alert-dismissible fade show" role="alert">
  		{{m}}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
	{%endfor%}







<form method="POST" class="col-6">

	{{register_form|crispy}}
	{%csrf_token%}
	<div class="container">
<button class="btn btn-primary">Register</button>
</form>
</div>
{%endblock%}